{{ if .Values.wso2.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micro-integrator-prometheus-service-monitor-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- range $key, $value := .Values.wso2.monitoring.prometheus.serviceMonitor.labels  }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
spec:
  jobLabel: monitoring
  selector:
      matchLabels:
          app: {{ .Release.Name }}
  namespaceSelector:
      matchNames:
          - {{ .Release.Namespace }}
  endpoints:
      - port: metrics
        interval: 1s
        Path: "/metric-service"
{{ end }}
